version: '3'
services:
  # see https://github.com/uc-cdis/ohif-orthanc-app-example
  dicom-viewer:
    # nginx reverse proxy
    image: quay.io/cdis/ohif-viewer:master
    ports:
      - 9880:80
    volumes:
    - ./data-volume/:/data/
    environment:
    - ORTHANC_HOST=localhost
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  orthanc:
    image: quay.io/cdis/orthanc-plugins:master
    # see https://blog.mikesir87.io/2019/03/sharing-network-namespaces-in-docker/
    network_mode: "service:dicom-viewer"
    # sample dicom available here: 
    #     https://medistim.com/dicom/
    volumes:
    - ./data-volume/:/data/
    healthcheck:
      test:
      - CMD
      - wget
      - -O
      - /dev/null
      - http://localhost/
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1536M
        reservations:
          cpus: '0.4'
          memory: 1024M
  postgres:
    image: postgres
    # see https://blog.mikesir87.io/2019/03/sharing-network-namespaces-in-docker/
    network_mode: "service:dicom-viewer"
    environment:
    - POSTGRES_DB=orthanc
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
