version: '3'
services:
   webapp:
      image: "quay.io/cdis/jupyter-slim:master"
      volumes:
         - ${DATA_VOLUME}:/data
      environment:
        - NAMESPACE=reuben
        - HOSTNAME=reuben.planx-pla.net
      entrypoint:
        - "start-notebook.sh"
      command:
        - "--NotebookApp.base_url=/lw-workspace/proxy"
        - "--NotebookApp.password=''"
        - "--NotebookApp.token=''"
      ports: 
         - "${SERVICE_PORT}:8888"
      healthcheck:
        test: ["CMD", "wget", "-O", "-", "http://localhost:8888/lw-workspace/proxy/"]
        interval: 1m30s
        timeout: 10s
        retries: 3
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 512M
          reservations:
            cpus: '0.3'
            memory: 256M
