version: '3.5'
services:
   webapp:
      image: "heliumdatastage/cloudtop-ohif:latest"
      network_mode: service:nginx
      entrypoint:
        - "/init"
      environment:
        - NAMESPACE=helium
        - HOSTNAME=helium.planx-pla.net
        - FRAME_ANCESTORS=https://helium.planx-pla.net
        - VNC_PW=heliumtest
        - USER_NAME=heliumtest
        - CLIENT_ID=
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1024M
          reservations:
            cpus: '1.0'
            memory: 1024M
   nginx:
      image: "quay.io/cdis/ws-nginx-proxy:2021.01"
      ports:
        - "${SERVICE_PORT}:7780"
      environment:
        - "APP_PORT=8080"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7780/_proxy_status"]
        interval: 1m30s
        timeout: 10s
        retries: 3
