version: '3'
services:
   webapp:
      image: "heliumdatastage/cloudtop-ohif:latest"
      volumes:
         - ${DATA_VOLUME}:/data
         - ${USER_VOLUME}:/home/jovyan/pd
      entrypoint: 
        - "/init"
      environment:
        - NAMESPACE=helium
        - HOSTNAME=helium.planx-pla.net
        - FRAME_ANCESTORS=https://helium.planx-pla.net
        - VNC_PW=heliumtes"
        - USER_NAME=heliumtest
        - CLIENT_ID=384421289758-frhkfv63tlt880o4cni2ovujomsi5en2.apps.googleusercontent.com  
      ports: 
        - "${SERVICE_PORT}:8080"
          #   healthcheck:
          #test: ["CMD", "wget", "-O", "-", "http://localhost:8888/lw-workspace/proxy/"]
          #interval: 1m30s
          #timeout: 10s
          #retries: 3
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1024M
          reservations:
            cpus: '1.0'
            memory: 1024M
