version: '2'
services:
   webapp:
      image: "heliumdatastage/jupyter-datascience:v0.0.3"
      volumes:
        - ${DATA_VOLUME}:/data
        - ${USER_VOLUME}:/home/jovyan/pd
      entrypoint:
        - /bin/bash
        - -c
        - start.sh jupyter lab --LabApp.token="" --NotebookApp.base_url="/lw-workspace/proxy"
      environment:
        - NAMESPACE=helium
        - HOSTNAME=helium.planx-pla.net
        - FRAME_ANCESTORS=https://helium.planx-pla.net
      ports: 
        - "${SERVICE_PORT}:8888"
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 512M
          reservations:
            cpus: '0.3'
            memory: 256M
